### ISSUE TITLE
InvalidMemoryOperationError

### ISSUE THREAD

**Issue by mzfhhhh** [eBookingServices/mysql-lited#3]
when i run this simple code in the unittest mode,the app will cause a memory exception after exiting

``` D
shared static this()
{       
    import mysql;
    auto client = new MySQLClient("host=127.0.0.1;user=root;pwd=test;db=motion");
}
```

core.exception.InvalidMemoryOperationError@src\core\exception.d(679): Invalid memory operation

**Comment by marcioapm** [comment]
Fixed with d9a0b16e91d95251a2d233972a8c623f88492765
