### ISSUE TITLE
mysql-lited-0.3.13,compile "conn.execute" error

### ISSUE THREAD

**Issue by mzfhhhh** [eBookingServices/mysql-lited#7]
mysql-lited-0.3.13,compile error
```D
conn.execute("insert into users (name, email) values (?, ?)", "frank", "thetank@cowabanga.com");
```

connection.d(246,4): Error: undefined identifier 'func'
connection.d(246,4): Error: undefined identifier 'file', did you mean variabl
e 'File'?
connection.d(246,4): Error: undefined identifier 'line', did you mean variabl
e 'Line'?
source\app.d(9,14): Error: template instance mysql.connection.Connection!(VibeSo
cket, cast(ConnectionOptions)0).Connection.execute!("source\\app.d", 9, string,
string) error instantiating
dmd failed with exit code 1.

**Comment by marcioapm** [comment]
Fixed in 0.3.14!

Thanks for reporting it! :)
